version: '3.6'

services:
  nginx:
    image: docker.pkg.github.com/marvincaspar/marvincaspar/web:latest
    networks:
      - web
    labels:
      traefik.http.routers.marvincaspar.rule: Host(`marvincaspar.dev`,`www.marvincaspar.dev`)
      traefik.http.routers.marvincaspar.entrypoints: websecure
      traefik.http.routers.marvincaspar.tls: true
      # traefik.http.routers.marvincaspar.middleware: https-redirect
      # traefik.http.middlewares.https-redirect.redirectscheme.scheme: https
      traefik.http.routers.marvincaspar.tls.certresolver: le

networks:
  web:
    driver: overlay
    external: true
