version: '3.6'

services:
  nginx:
    image: docker.pkg.github.com/marvincaspar/marvincaspar/web:latest
    networks:
      - web
    labels:
      traefik.http.routers.marvincaspar.rule: Host(`i-am-a.dev`,`www.i-am-a.dev`,`caspar.dev`,`www.caspar.dev`,`marvincaspar.de`,`www.marvincaspar.de`,`mail.marvincaspar.de`)
      traefik.http.routers.marvincaspar.middlewares: hsts-header
      traefik.http.routers.marvincaspar.tls.options: intermediate
      
      traefik.http.routers.marvincaspar-insecure.rule: Host(`i-am-a.dev`,`www.i-am-a.dev`,`caspar.dev`,`www.caspar.dev`,`marvincaspar.de`,`www.marvincaspar.de`,`mail.marvincaspar.de`)
      traefik.http.routers.marvincaspar-insecure.middlewares: redirect-to-https,hsts-header

      traefik.http.routers.marvincaspar.tls.certresolver: le

networks:
  web:
    driver: overlay
    external: true
